//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentPerformanceStatistics
    {
        public string AgentName { get; set; }
        public Nullable<int> NumberOfPoliciesSold { get; set; }
        public Nullable<decimal> TotalSalesAmount { get; set; }
        public Nullable<decimal> AverageSalesAmount { get; set; }
    }
}
