//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        public Agents()
        {
            this.Policies = new HashSet<Policies>();
        }
    
        public int IdAgent { get; set; }
        public int IdUser { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public int IdGender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int IdPosition { get; set; }
        public decimal Salary { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Position Position { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<Policies> Policies { get; set; }
    }
}
