//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claims
    {
        public Claims()
        {
            this.ClaimPayments = new HashSet<ClaimPayments>();
        }
    
        public int IdClaim { get; set; }
        public string ClaimNumber { get; set; }
        public System.DateTime DateFiled { get; set; }
        public int IdStatus { get; set; }
        public string Description { get; set; }
        public int IdPolicy { get; set; }
    
        public virtual ICollection<ClaimPayments> ClaimPayments { get; set; }
        public virtual Policies Policies { get; set; }
        public virtual Status Status { get; set; }
    }
}
