//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimStatistics
    {
        public string Status { get; set; }
        public Nullable<int> NumberOfClaims { get; set; }
        public Nullable<decimal> TotalClaimAmount { get; set; }
        public Nullable<decimal> AverageClaimAmount { get; set; }
    }
}
