//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        public Gender()
        {
            this.Agents = new HashSet<Agents>();
            this.Clients = new HashSet<Clients>();
            this.Drivers = new HashSet<Drivers>();
            this.Owner = new HashSet<Owner>();
        }
    
        public int IdGender { get; set; }
        public string GenderName { get; set; }
    
        public virtual ICollection<Agents> Agents { get; set; }
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual ICollection<Drivers> Drivers { get; set; }
        public virtual ICollection<Owner> Owner { get; set; }
    }
}
