//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public Owner()
        {
            this.Policies = new HashSet<Policies>();
        }
    
        public int IdOwner { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Pantronymic { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public int IdAddress { get; set; }
        public int IdGender { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Policies> Policies { get; set; }
    }
}
