//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policies
    {
        public Policies()
        {
            this.Claims = new HashSet<Claims>();
            this.PolicyPayments = new HashSet<PolicyPayments>();
            this.Drivers = new HashSet<Drivers>();
            this.InsuranceCategories = new HashSet<InsuranceCategories>();
            this.InsuranceRisks = new HashSet<InsuranceRisks>();
        }
    
        public int IdPolicy { get; set; }
        public string PolicyNumber { get; set; }
        public decimal CoverageAmount { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int IdClient { get; set; }
        public int IdOwner { get; set; }
        public int IdVehicles { get; set; }
        public int IdAgent { get; set; }
        public int IdStatus { get; set; }
        public Nullable<decimal> InsuranseCost { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual ICollection<Claims> Claims { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual ICollection<PolicyPayments> PolicyPayments { get; set; }
        public virtual Status Status { get; set; }
        public virtual Vehicles Vehicles { get; set; }
        public virtual ICollection<Drivers> Drivers { get; set; }
        public virtual ICollection<InsuranceCategories> InsuranceCategories { get; set; }
        public virtual ICollection<InsuranceRisks> InsuranceRisks { get; set; }
    }
}
