//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyPayments
    {
        public int IdPayment { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DatePaid { get; set; }
        public int IdPolicy { get; set; }
    
        public virtual Policies Policies { get; set; }
    }
}
