//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyCategoryStatistics
    {
        public string CategoryName { get; set; }
        public Nullable<int> NumberOfPolicies { get; set; }
        public Nullable<decimal> TotalCoverageAmount { get; set; }
        public Nullable<decimal> AverageCoverageAmount { get; set; }
    }
}
