//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.Agents = new HashSet<Agents>();
            this.Clients = new HashSet<Clients>();
        }
    
        public int IdUser { get; set; }
        public string LoginName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public System.DateTime PasswordDate { get; set; }
        public string PasswordRecovery { get; set; }
        public int IdRole { get; set; }
    
        public virtual ICollection<Agents> Agents { get; set; }
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual Role Role { get; set; }
    }
}
