//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        public Vehicles()
        {
            this.Policies = new HashSet<Policies>();
            this.Clients = new HashSet<Clients>();
        }
    
        public int IdVehicles { get; set; }
        public string RegistrationNumber { get; set; }
        public string Country { get; set; }
        public string VIN { get; set; }
        public int IdVehicleCategory { get; set; }
        public int IdVehicleType { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string Generation { get; set; }
        public double Power { get; set; }
        public int IdUsagePurpose { get; set; }
        public Nullable<int> IdVehicleDocuments { get; set; }
        public string PeriodOfUse { get; set; }
    
        public virtual ICollection<Policies> Policies { get; set; }
        public virtual UsagePurpose UsagePurpose { get; set; }
        public virtual VehicleCategory VehicleCategory { get; set; }
        public virtual VehicleDocuments VehicleDocuments { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual ICollection<Clients> Clients { get; set; }
    }
}
