//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleClientView
    {
        public int IdVehicles { get; set; }
        public string RegistrationNumber { get; set; }
        public string Country { get; set; }
        public string VIN { get; set; }
        public int IdVehicleCategory { get; set; }
        public int IdVehicleType { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string Generation { get; set; }
        public double Power { get; set; }
        public int IdUsagePurpose { get; set; }
        public Nullable<int> VehicleDocumentsId { get; set; }
        public string PeriodOfUse { get; set; }
        public int ClientId { get; set; }
        public int IdVehicle { get; set; }
        public System.DateTime DocumentIssueDate { get; set; }
        public string DocumentNumber { get; set; }
        public string DocumentSeries { get; set; }
        public string TypeDocument { get; set; }
        public int IdVehicleDocuments { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public int IdAddress { get; set; }
        public int IdClient { get; set; }
        public int IdGender { get; set; }
        public int IdUser { get; set; }
        public string PassportNumber { get; set; }
        public string PassportSeries { get; set; }
    }
}
