//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDocuments
    {
        public VehicleDocuments()
        {
            this.Vehicles = new HashSet<Vehicles>();
        }
    
        public int IdVehicleDocuments { get; set; }
        public string TypeDocument { get; set; }
        public string DocumentSeries { get; set; }
        public string DocumentNumber { get; set; }
        public System.DateTime DocumentIssueDate { get; set; }
    
        public virtual ICollection<Vehicles> Vehicles { get; set; }
    }
}
