//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleType
    {
        public VehicleType()
        {
            this.Vehicles = new HashSet<Vehicles>();
        }
    
        public int IdVehicleType { get; set; }
        public string VehicleTypeName { get; set; }
    
        public virtual ICollection<Vehicles> Vehicles { get; set; }
    }
}
